name: Build MinecraftPE for Windows XP

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install VS2017 Build Tools
        run: |
          curl -o vs_buildtools.exe https://aka.ms/vs/15/release/vs_buildtools.exe
          .\vs_buildtools.exe --quiet --wait --norestart --nocache `
            --add Microsoft.VisualStudio.Workload.VCTools `
            --add Microsoft.VisualStudio.Component.WinXP

      - name: Setup CMake 3.21
        uses: jwlawson/actions-setup-cmake@v1.14
        with:
          cmake-version: '3.21.0'

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Build
        shell: pwsh
        run: |
          $ninjaDir = (Get-Command ninja).Source | Split-Path
          .\build-xp.ps1 -Clean -NinjaDir $ninjaDir

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: MinecraftPE-WinXP
          path: build-xp\MinecraftPE.exe
